services:
  php:
    image: thecodingmachine/php:${PHP_VERSION:-8.1}-v4-cli
    container_name: attribute_php
    environment:
      - PHP_EXTENSION_XDEBUG=1
      - XDEBUG_MODE=off
    init: true
    restart: "no"
    volumes:
      - ./:/usr/src/app
